---
title: "prob05-cp01"
author: "Ana Godoy"
date: "30 de julho de 2018"
output: html_document
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(plotly)
library(lubridate)
library(boot)
library(resample)

theme_set(theme_bw())

```
#Os Dados

```{r}
dados = read_csv(("../speed-dating/speed-dating.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(),
                                    gender	= col_double(),
                                    order	= col_double(), 
                                    pid	= col_double(), 
                                    int_corr = col_double(), 
                                    samerace = col_double(), 
                                    age_o	= col_double(), 
                                    age	= col_double(), 
                                    field	= col_character(),
                                    race	= col_character(),
                                    from	= col_character(),
                                    career	= col_character(),
                                    sports	= col_double(), 
                                    tvsports	= col_double(), 
                                    exercise	= col_double(), 
                                    dining	= col_double(), 
                                    museums	= col_double(), 
                                    art	= col_double(), 
                                    hiking	= col_double(), 
                                    gaming	= col_double(), 
                                    clubbing	= col_double(), 
                                    reading	= col_double(), 
                                    tv	= col_double(), 
                                    theater	= col_double(), 
                                    movies	= col_double(), 
                                    concerts	= col_double(), 
                                    music	= col_double(), 
                                    shopping	=col_double(), 
                                    yoga	= col_double(), 
                                    attr	= col_double(), 
                                    sinc	= col_double(), 
                                    intel	= col_double(), 
                                    fun	= col_double(), 
                                    amb	= col_double(), 
                                    shar	= col_double(), 
                                    like	= col_double(), 
                                    prob	= col_double(), 
                                    match_es = col_double(), 
                                    attr3_s	= col_double(), 
                                    sinc3_s	= col_double(), 
                                    intel3_s	= col_double(), 
                                    fun3_s	= col_double(), 
                                    amb3_s= col_double()))
dados
```
